apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: alatagichetandevops/mavenwebapp:1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: maven-service
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
